# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cleed < Formula
  desc "A simple feed reader for the command line"
  homepage "https://github.com/radulucut/cleed"
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/radulucut/cleed/releases/download/v0.1.5/cleed_Darwin_x86_64.tar.gz"
      sha256 "6537552de1b07448bdc27bc32c2b5afa49dc98fdb9a3bfebf44efab693391e93"

      def install
        bin.install "cleed"
      end
    end
    on_arm do
      url "https://github.com/radulucut/cleed/releases/download/v0.1.5/cleed_Darwin_arm64.tar.gz"
      sha256 "38a32e06e6a77a944e647e1a7d7cd56c13d23a0333860dd5b5c7204fac9bf209"

      def install
        bin.install "cleed"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/radulucut/cleed/releases/download/v0.1.5/cleed_Linux_x86_64.tar.gz"
        sha256 "1ea46572f8354f0ef1902d9dce383cd1578d8c225d7c24171d27a48ef89f2b4d"

        def install
          bin.install "cleed"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/radulucut/cleed/releases/download/v0.1.5/cleed_Linux_arm64.tar.gz"
        sha256 "e7277b8327c97c4f3dd652d56d32b79540da202c46b5f5c9967d74084e00c3c7"

        def install
          bin.install "cleed"
        end
      end
    end
  end
end
